### ISSUE TITLE
org-store-link: Symbol’s value as variable is void: name

### ISSUE THREAD

**Issue by jsilve24** [ag91/ol-emacs-slack#5]
I am getting the following error when trying to use `org-store-link` in a Slack Message Buffer. 

`Symbol’s value as variable is void: name`

Any idea what thats about or how to fix?

Thank you!
Justin

**Comment by ag91** [comment]
could you try to evaluate the following forms in your slack buffer?

This is to find the current slack buffer object:
`slack-current-buffer`

This is to get the team:
`(slack-buffer-team slack-current-buffer)`

And this is the bit I think is failing on your side:
`(oref team (slack-buffer-team slack-current-buffer))`

If it does fail, please share the returns of the others (or if private info is in there, the keys of the second)

**Comment by jsilve24** [comment]
```
> slack-message-buffer
#s(slack-message-buffer "T019KXX4NA0" #<buffer *Slack - Silverman Lab : John Doe> "D01CPA5822RJ" "1642186847.007000" "1649101012.144619" #<overlay from 21711 to 21743 in *Slack - Silverman Lab : John Doe>
			(nil)
			"1649100953.770759" "bmV4dF90czoxNjQyMTg1NzM5MDA2OTAw")
```

The second command had a bunch of private info so I am just sharing the top of out output. 

```
#sslack-team "T019KEZ4NA0" "xoxc-XXXXXXX" "My Lab" "myusername"
	      (:id "U0196HE72QN" :name "me")
	      "U0196HE72QN" "me" #shash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
							    "C02XXXAE" #sslack-channel "C02RXXXAE" 100010116 0 0 nil #s(hash-table size 300 test equal rehash-size 1.5 rehash-threshold 0.8125 data
																	   ())
											    "0" "mpdm-justinsilverman--mxx2--zxxx3-1" "mpdm-justinsilverman--mxx72--zxx53-1" 3 "U01XXXN" nil t nil nil nil nil nil t t nil t nil nil nil nil nil
											    (:value "Group messaging with: @justinsilverman @map5672 @zxxx3" :creator "U01XXXN" :last_set 1640110116)
											    ("T0XXX0")
											    (:value "" :creator "" :last_set 0)
											    "U0196HE72QN" U0196H
```

The final one evaluates fine actually...
`"My Lab"`

**Comment by jsilve24** [comment]
Interestingly thought this fails

```
(let* (buf slack-current-buffer)
           (team (slack-buffer-team buf))
           (team-name (oref team name)))
```
with the same error (void team)

**Comment by jsilve24** [comment]
I think its actually the last line of this let chain that is causing errors

```


(let* (buf slack-current-buffer)
 (team (slack-buffer-team buf))
 (team-name (oref team name))
 (room (slack-buffer-room buf))
 (room-name (slack-room-name room team))
 (ts (org-get-at-bol 'ts))
 (formatted_ts (org-get-at-bol 'lui-formatted-time-stamp))
 (link (ol/slack-format-link team room ts)))
```
Everything else works as expected

**Comment by jsilve24** [comment]
Oddly I think its actually this line:

```
(defun ol/slack-format-link (team room &optional timestamp)
  "Format the link to go back to the `ROOM' of the `TEAM', possibly at the `TIMESTAMP'."
  (let ((link (format "%s&%s" (slack-team-id team) (oref room id))))
    (when timestamp
      (setq link (format "%s&ts:%s" link timestamp)))
    link))
```

Where is the variable id supposed to be defined?

**Comment by jsilve24** [comment]
If i change the form `(oref room id)` to `"foo"` then I don't get any error.

**Comment by ag91** [comment]
ah very interesting, that's great progress! What sort of channel are you trying to store a link from? I mean is it a 1-1 conversation or a channel you created by selecting some users or a private channel or a public channel? 

As far as I understand, `(oref room id)` is an object accessor in Lisp. Emacs Slack is written in Object Oriented style and a room object has an id attribute. That is required for my little mode to find the chat you bookmarked.

**Comment by jsilve24** [comment]
its a 1-1 conversation I belive its a direct message channel that I select through `slack-select-rooms`

**Comment by jsilve24** [comment]
Is it possible to just shield that lisp form by testing if id exists?

**Comment by ag91** [comment]
mmm, that will not work: it sounds definitely strange that your slack buffer doesn't have a room-id. Without that your org-link cannot be taken! The only thing I can do is to raise a better defined error than what you are receiving.

**Comment by ag91** [comment]
Anyway, is this error happening in all the rooms you selected so far or only for this one?

**Comment by jsilve24** [comment]
So i had a bit more time to dig into this today. Turns out that these errors only turn up when these functions are run in entirety -- when I step through ol/slack-store-link in edebug everything works fine. I just have to step into the ol/slack-format-link function to avoid the id error. 

WTF is going on?  Is this some weirdness of EIEIO or something?

**Comment by ag91** [comment]
Thanks for looking into this. I am not sure how to help. I tested this on Emacs 27 and 28.
I am not sure what the debugger does that tricks the function into working. 
Maybe you can still test with printlns?
Like maybe try to redefine the function like this:
```
(defun ol/slack-store-link ()
  "Store a link to a slack group page."
  (when (or (eq major-mode 'slack-message-buffer-mode)
            (eq major-mode 'slack-thread-message-buffer-mode))
    (let* ((buf slack-current-buffer)
           (_ (message "--1 %s" buf))
           (team (slack-buffer-team buf))
           (_ (message "--2 %s" team))
           (team-name (oref team name))
           (_ (message "--3 %s" team-name))
           (room (slack-buffer-room buf))
           (_ (message "--4 %s" room))
           (room-name (slack-room-name room team))
           (_ (message "--5 %s" room-name))
           (ts (org-get-at-bol 'ts))
           (_ (message "--6 %s" ts))
           (formatted_ts (org-get-at-bol 'lui-formatted-time-stamp))
           (_ (message "--7 %s" formatted_ts))
           (link (ol/slack-format-link team room ts))
           (_ (message "--8 %s" link))
           (description (concat
                         "Slack message in #"
                         room-name
                         (if formatted_ts (format " at %s" formatted_ts) "")
                         (if ts
                             (concat ": "(s-trim (buffer-substring-no-properties
                                                  (point-at-bol)
                                                  (point-at-eol
                                                   ))))
                           "")))
           (_ (message "--9 %s" description)))
      (org-link-store-props
       :type "emacs-slack"
       :link (concat "emacs-slack:" link)
       :description description))))
``` 
and see till what point it prints in the Messages buffer?

**Comment by jsilve24** [comment]
So ultimately it seems to have been a problem with accessing the elements of the team and room objects within the ol/slack-format-link function. In contrast if I did the accessing outside in the ol/slack-store-link function then it works fine. 

I have no idea why. This code seems to work for me with (what I think) is no conceptual difference or impact on the rest of the package. 

```
(defun ol/slack-store-link ()
  "Store a link to a slack group page."
  (when (or (eq major-mode 'slack-message-buffer-mode)
            (eq major-mode 'slack-thread-message-buffer-mode))
    (let* ((buf slack-current-buffer)
           (team (slack-buffer-team buf))
           (team-name (oref team name))
           (room (slack-buffer-room buf))
           (room-name (slack-room-name room team))
           (ts (org-get-at-bol 'ts))
           (formatted_ts (org-get-at-bol 'lui-formatted-time-stamp))
	   (room-id (oref room id))
	   (team-id (slack-team-id team))
           (link (ol/slack-format-link team-id room-id ts))
	   (description (concat
                         "Slack message in #"
                         room-name
                         (if formatted_ts (format " at %s" formatted_ts) "")
                         (if ts
                             (concat ": "(s-trim (buffer-substring-no-properties
                                                  (point-at-bol)
                                                  (point-at-eol
                                                   ))))
                           ""))))
      (org-link-store-props
       :type "emacs-slack"
       :link (concat "emacs-slack:" link)
       :description description))))


(defun ol/slack-format-link (team-id room-id &optional timestamp)
  "Format the link to go back to the `ROOM' of the `TEAM', possibly at the `TIMESTAMP'."
  (let ((link (format "%s&%s" team-id room-id)))
    (when timestamp
      (setq link (format "%s&ts:%s" link timestamp)))
    link))

```

**Comment by jsilve24** [comment]
Previous comment seems incorrect, still having the same problem. 
Weirdly I am getting different things if I edit the source of the package with the verbose ol/slack-store-link vs. if I evaluate the function interactively... I am very confused going to post on some other sites to see if others have ideas.

**Comment by jsilve24** [comment]
Alright. I figured it out. all of this was from two missing require statements. I am going to put together a pull request that fixes the issue.

**Comment by ag91** [comment]
thanks @jsilve24 ! Sorry for missing those requires and the time you spent. Still that was a great investigation on your side: that's some amazing contribution :)
